database:
  host: localhost
  port: 3306
  user: root
  password: zhangchao321
  dbname: doovvvblog
server:
  host: localhost
  port: 3000
  appmode: debug
  secret: dsaj349052b32j
  file_path: D:\code\golang\doovvvblog